```python
i = 42       # integer
i = 2**77    # Integers have arbitrary precision
g = 3.14     # floating point number
c = 2 - 3j   # Complex number
b = True     # boolean
s = "Hello!" # String (Unicode)
q = b'Hello' # bytes (8-bit values)
```

In [2]:

a = list(range(10))
b = [0]*10

for i in a:
    b[i] = a[i]**3
print(b)


[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


In [4]:
value = ('a1','b2','c3')
print(type(value))
print(value)
print(dict(value))

<class 'tuple'>
('a1', 'b2', 'c3')
{'a': '1', 'b': '2', 'c': '3'}


In [19]:
#打印斐波那契数列
a = 0
b = 1
for i in range(10):
    print(a)
    a,b = b,a+b

def fib(n):
    if n in (1, 2):
        return 1
    return fib(n - 1) + fib(n - 2)


# 打印前20个斐波那契数
for i in range(1, 21):
    print(fib(i))
    

0
1
1
2
3
5
8
13
21
34
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765


In [ ]:
%%timeit
sum = 0

for i in range(10000):
    sum += i+1

print(sum)

In [20]:
class Student:
    """学生"""

    def __init__(self, name, age):
        """初始化方法"""
        self.name = name
        self.age = age

    def study(self, course_name):
        """学习"""
        print(f'{self.name}正在学习{course_name}.')

    def play(self):
        """玩耍"""
        print(f'{self.name}正在玩游戏.')
    
    def __repr__(self):
        return f'{self.name}: {self.age}'


stu1 = Student('骆昊', 40)
print(stu1)        # 骆昊: 40
students = [stu1, Student('李元芳', 36), Student('王大锤', 25)]
print(students)    # [骆昊: 40, 李元芳: 36, 王大锤: 25]

骆昊: 40
[骆昊: 40, 李元芳: 36, 王大锤: 25]


In [ ]:
import time


# 定义数字时钟类
class Clock(object):
    """数字时钟"""

    def __init__(self, hour=0, minute=0, second=0):
        """初始化方法
        :param hour: 时
        :param minute: 分
        :param second: 秒
        """
        self.hour = hour
        self.min = minute
        self.sec = second

    def run(self):
        """走字"""
        self.sec += 1
        if self.sec == 60:
            self.sec = 0
            self.min += 1
            if self.min == 60:
                self.min = 0
                self.hour += 1
                if self.hour == 24:
                    self.hour = 0

    def show(self):
        """显示时间"""
        return f'{self.hour:0>2d}:{self.min:0>2d}:{self.sec:0>2d}'


# 创建时钟对象
clock = Clock(23, 59, 58)
while True:
    # 给时钟对象发消息读取时间
    print(clock.show())
    # 休眠1秒钟
    time.sleep(1)
    # 给时钟对象发消息使其走字
    clock.run()

In [27]:
class Point(object):
    """屏面上的点"""

    def __init__(self, x=0, y=0):
        """初始化方法
        :param x: 横坐标
        :param y: 纵坐标
        """
        self.x, self.y = x, y

    def distance_to(self, other):
        """计算与另一个点的距离
        :param other: 另一个点
        """
        dx = self.x - other.x
        dy = self.y - other.y
        return (dx * dx + dy * dy) ** 0.5

    def __str__(self):
        return f'({self.x}, {self.y})'


# 示例点对象
p1 = Point(1, 2)
p2 = Point(4, 6)
print(p1, p2)
print(p1.distance_to(p2))

(1, 2) (4, 6)
5.0


In [28]:
class Student:

    def __init__(self, name, age):
        self.__name = name
        self.__age = age

    def study(self, course_name):
        print(f'{self.__name}正在学习{course_name}.')


stu = Student('王大锤', 20)
stu.study('Python程序设计')
print(stu._Student__name, stu._Student__age)

王大锤正在学习Python程序设计.
王大锤 20


In [3]:
import numpy as np

x = np.array([1, 2, 3])
print(id(x))                        # get the memory-ID of x
np.add(x, x, x)              # Third argument is output array
np.add(x, x, x)
print(x)
print(id(x))                        # get the memory-ID of x
                             # - notice  it is the same

2122726173136
[ 4  8 12]
2122726173136


In [11]:
import numpy as np

a = np.array([1, 2, 3])
a = a[::-1] 
print(a)

boundary_array = np.ones((5, 5))
boundary_array[[0,-1], :] = 0
boundary_array[:, [0,-1]] = 0
print(boundary_array)

x = np.random.rand(20)
print(x)
y = x + 10*(x > 0.2)*(x < 0.7)   #(x > 0.2)*(x < 0.7)将返回一个布尔数组，True对应1，False对应0
print(y)

[3 2 1]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[0.28005509 0.59883238 0.41007625 0.23698442 0.59641436 0.63933762
 0.83545908 0.02208609 0.53017341 0.14691656 0.51060089 0.55021578
 0.15683976 0.1026048  0.50895697 0.3232104  0.98645219 0.65788631
 0.85632939 0.42700152]
[10.28005509 10.59883238 10.41007625 10.23698442 10.59641436 10.63933762
  0.83545908  0.02208609 10.53017341  0.14691656 10.51060089 10.55021578
  0.15683976  0.1026048  10.50895697 10.3232104   0.98645219 10.65788631
  0.85632939 10.42700152]
